#!/bin/sh
# Generates docs/README.md from the docs tree.
# Usage: scripts/gen-docs-index.sh
# Called by: make docs-index   (regenerate)
#            make check-docs-index (fail if stale)

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOCS="$ROOT/docs"
OUT="$DOCS/README.md"

# Extract the first # heading from a file, or fall back to the filename stem.
title() {
    t=$(grep -m1 "^# " "$1" 2>/dev/null | sed 's/^# //')
    if [ -z "$t" ]; then
        t=$(basename "$1" .md)
    fi
    printf '%s' "$t"
}

{
    printf '# YAAMon Documentation\n\n'
    printf '<!-- generated by scripts/gen-docs-index.sh — run `make docs-index` to update -->\n\n'

    for section in installation configuration user-guide security troubleshooting reference design; do
        dir="$DOCS/$section"
        [ -d "$dir" ] || continue

        # Section heading — link to README if present, else to the section dir
        if [ -f "$dir/README.md" ]; then
            printf '## [%s](%s/README.md)\n' "$(title "$dir/README.md")" "$section"
        else
            printf '## %s\n' "$section"
        fi

        # Direct .md files (non-README), sorted
        entries=0
        for f in $(find "$dir" -maxdepth 1 -name "*.md" ! -name "README.md" | sort); do
            base=$(basename "$f")
            printf '\n- [%s](%s/%s)' "$(title "$f")" "$section" "$base"
            entries=1
        done
        [ "$entries" = "1" ] && printf '\n'

        # One level of subdirectories, sorted
        for sub in $(find "$dir" -maxdepth 1 -mindepth 1 -type d | sort); do
            subname=$(basename "$sub")
            printf '\n'
            if [ -f "$sub/README.md" ]; then
                printf -- '- **[%s](%s/%s/README.md)**\n' \
                    "$(title "$sub/README.md")" "$section" "$subname"
            fi
            for f in $(find "$sub" -maxdepth 1 -name "*.md" ! -name "README.md" | sort); do
                base=$(basename "$f")
                printf '  - [%s](%s/%s/%s)\n' "$(title "$f")" "$section" "$subname" "$base"
            done
        done

        printf '\n'
    done
} > "$OUT"
